/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;
import java.awt.Color;
import java.util.ArrayList;
import java.io.File;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Ibrahim
 */
public class Form4 extends javax.swing.JFrame {

    ArrayList<Ticket> arr;
    /**
     * Creates new form Form4
     */
    public Form4() {
        initComponents();
        jLabel4.setVisible(false);
    }
    
    public Form4(ArrayList<Ticket> arr) {
        initComponents();
        jLabel4.setVisible(false);
        this.arr=arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(598, 750));
        setMinimumSize(new java.awt.Dimension(598, 750));
        setPreferredSize(new java.awt.Dimension(598, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 227, 200));
        jLabel2.setText("CANCEL BOOKING");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(2, 145, 116));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< MAIN MENU");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 40));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSPORT NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 36));

        jTextField1.setBackground(new java.awt.Color(5, 17, 21));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ERROR! NO TICKET BOOKED UNDER THIS PASSPORT!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 590, 60));

        jButton2.setBackground(new java.awt.Color(2, 145, 116));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/back3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Form1 f1=new Form1(arr);
        f1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String txt=jTextField1.getText();
        
        if (txt.equals(""))
        {
            jLabel4.setVisible(true);
            jLabel4.setForeground(new java.awt.Color(246, 115, 124));
            jLabel4.setText("ERROR! PASSPORT NUMBER REQUIRED");
        }
        
        else
        {
        
        int chk=-1;
        for (int i=0; i<arr.size(); i++)
        {
            if(jTextField1.getText().equals(arr.get(i).passenger.passportNum))
            {
                chk=i;
                break;
            }
        }
        
        if (chk==-1) 
        {
            jLabel4.setVisible(true);
            jLabel4.setText("ERROR! NO TICKET BOOKED UNDER THIS PASSPORT");
            jLabel4.setForeground(new java.awt.Color(246, 115, 124));
        }
        
        else
        {
            jLabel4.setVisible(true);
            jLabel4.setText("BOOKING CANCELLED SUCCESSFULLY!");
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            
            String nm=arr.get(chk).passenger.name+"_"+arr.get(chk).flight.flightNumber
                    +"_Ticket.txt";
            File fl = new File(nm);
            fl.delete();
            
            arr.remove(chk);
            if (chk!=0)
            { arr.get(0).saveArraylistToFile(arr); }
            else 
            {
                try
            {
                FileWriter myWriter = new FileWriter("arrayList.txt");
                BufferedWriter b=new BufferedWriter(myWriter);
                b.write("");
            }
                catch(IOException e) { }
            } 
            
        }
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
