/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;
import java.util.ArrayList;
import java.io.File;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Ibrahim
 */
public class Form1 extends javax.swing.JFrame {
    
     ArrayList<Ticket> arr;

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        arr=new ArrayList<Ticket>();
        String str="";
        
        try
        {
        FileReader myObj = new FileReader("arrayList.txt");
        BufferedReader b1=new BufferedReader(myObj);
        String class1="",org1="",des1="",date1="",name1="",pNum1="",isRound1="",
                flNum="",seatNum="",bGate="",lug="";
               
        while( (str=b1.readLine())!=null)
        {
            for (int i=0; i<str.length(); i++)
            {
                if (i<str.indexOf("*")) { class1+=str.charAt(i); }
                if (i>str.indexOf("*") && i<str.indexOf("/")) { org1+=str.charAt(i); }
                if (i>str.indexOf("/") && i<str.indexOf(".")) { des1+=str.charAt(i); }
                if (i>str.indexOf(".") && i<str.indexOf(",")) { date1+=str.charAt(i); }
                if (i>str.indexOf(",") && i<str.indexOf(";")) { name1+=str.charAt(i); }
                if (i>str.indexOf(";") && i<str.indexOf("?")) { pNum1+=str.charAt(i); }
                if (i>str.indexOf("?") && i<str.indexOf("!")) { isRound1+=str.charAt(i); }
                if (i>str.indexOf("!") && i<str.indexOf("&")) { lug+=str.charAt(i); }
                if (i>str.indexOf("&") && i<str.indexOf("$")) { seatNum+=str.charAt(i); }
                if (i>str.indexOf("$") && i<str.indexOf("#")) { flNum+=str.charAt(i); }       
                if (i>str.indexOf("#")) { bGate+=str.charAt(i); }
            }
            
            boolean isRoundT=true;
            if (isRound1.equals("false")) { isRoundT=false; }
            else { isRoundT=true; }
            
            int lug1=Integer.parseInt(lug);
            
            if (class1.equals("ECONOMY"))
            {
                Economy ec1=
                new Economy(org1,des1,date1,name1,pNum1,isRoundT,lug1,flNum,seatNum,bGate);
                arr.add(ec1);
            }
            
            else if (class1.equals("BUSINESS"))
            {
                Business bs1=
                new Business(org1,des1,date1,name1,pNum1,isRoundT,lug1,flNum,seatNum,bGate);
                arr.add(bs1);
            }
            
            else 
            {
                First fs1=
                new First(org1,des1,date1,name1,pNum1,isRoundT,lug1,flNum,seatNum,bGate);
                arr.add(fs1);
            }
                
            
          
            
        }
        
        }
        
        catch(IOException e) {}
       
        
        
    }
    
    public Form1(ArrayList<Ticket> arr) {
        initComponents();
        this.arr=arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(598, 750));
        setMinimumSize(new java.awt.Dimension(598, 750));
        setPreferredSize(new java.awt.Dimension(598, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(90, 227, 200));
        jLabel1.setText("MAIN MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(2, 145, 116));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL BOOKING");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 145, 116), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 220, 70));

        jButton2.setBackground(new java.awt.Color(2, 145, 116));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VIEW TICKET");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 220, 67));

        jButton3.setBackground(new java.awt.Color(2, 145, 116));
        jButton3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BOOK TICKET");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 145, 116), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 220, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/back1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Form3 f3=new Form3(arr);
        f3.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Form4 f4=new Form4(arr);
      f4.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Form2 f=new Form2(arr);
      f.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
