/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;
import java.util.ArrayList;
import java.awt.Color;

/**
 *
 * @author Ibrahim
 */
public class Form2 extends javax.swing.JFrame {
    
    ArrayList<Ticket> arr;

    /**
     * Creates new form Form2
     */
    public Form2() {
        initComponents();
        jButton1.setVisible(false);  
        jPanel2.setVisible(false);  
    }
    
    public Form2(ArrayList<Ticket> arr) {
        initComponents();
        jButton1.setVisible(false);
        jPanel2.setVisible(false);
        this.arr=arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(598, 750));
        setMinimumSize(new java.awt.Dimension(598, 750));
        setPreferredSize(new java.awt.Dimension(598, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(90, 227, 200));
        jLabel1.setText("ENTER DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(16, 39, 47));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TICKET BOOKED SUCCESSFULLY!");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 330, 30));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL FARE    $");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, -1));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(90, 227, 200));
        jLabel13.setText("300.0");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 610, 390));

        jPanel1.setBackground(new java.awt.Color(16, 39, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 61, 28));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSPORT NUMBER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 28));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORIGIN CITY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 156, 28));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESTINATION CITY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 28));

        jTextField1.setBackground(new java.awt.Color(5, 17, 21));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 8, 180, 30));

        jTextField2.setBackground(new java.awt.Color(5, 17, 21));
        jTextField2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 48, 180, 30));

        jComboBox1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZURICH (ZRH)", "NEW YORK (JFK)", "VIENNA (VIE)", "ROME (FCO)", "LONDON (LHR)", "SEATTLE (SEA)", "MOSCOW (DME)", "MILAN (MXP)", "PRAGUE (PRG)" }));
        jComboBox1.setSelectedIndex(4);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 180, 28));

        jComboBox2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZURICH (ZRH)", "NEW YORK (JFK)", "VIENNA (VIE)", "ROME (FCO)", "LONDON (LHR)", "SEATTLE (SEA)", "MOSCOW (DME)", "MILAN (MXP)", "PRAGUE (PRG)" }));
        jComboBox2.setEditor(null);
        jComboBox2.setFocusable(false);
        jComboBox2.setKeySelectionManager(null);
        jComboBox2.setLightWeightPopupEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 28));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEPARTURE DATE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 28));

        jTextField3.setBackground(new java.awt.Color(5, 17, 21));
        jTextField3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("01-JAN");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 28));

        jSlider1.setBackground(new java.awt.Color(5, 17, 21));
        jSlider1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(12);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(1);
        jSlider1.setOpaque(false);
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CLASS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 40, 30));

        jComboBox3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ECONOMY", "BUSINESS", "FIRST" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 180, 30));

        jSeparator1.setBackground(new java.awt.Color(2, 145, 116));
        jSeparator1.setForeground(new java.awt.Color(2, 145, 116));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator1.setMaximumSize(new java.awt.Dimension(50, 30));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 30));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 420, 10));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LUGGAGE (KG)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, 30));

        jComboBox4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ONE-WAY", "ROUND" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 180, 30));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DURATION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 90, 30));

        jSeparator2.setBackground(new java.awt.Color(2, 145, 116));
        jSeparator2.setForeground(new java.awt.Color(2, 145, 116));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator2.setMaximumSize(new java.awt.Dimension(50, 30));
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 30));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 420, 10));

        jButton2.setBackground(new java.awt.Color(2, 145, 116));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BOOK");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 370, 40));

        jButton1.setBackground(new java.awt.Color(206, 63, 73));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 490, 550));

        jButton3.setBackground(new java.awt.Color(2, 145, 116));
        jButton3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("< MAIN MENU");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/back3.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Form1 f1=new Form1(arr);
        f1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        boolean b=(jTextField1.getText()).equals("") || (jTextField2.getText()).equals("")
            || (jTextField3.getText()).equals("") ;
        
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();
        
        int checkS1=0, checkS2=0, checkS3=0;
        
        for (int i=0; i<s1.length(); i++)
        {
            char c1=s1.charAt(i);
            if (c1=='*' || c1=='/' || c1=='.' || c1==',' || c1==';' || c1=='?' || c1=='!'
                    || c1=='&' || c1=='$' || c1=='#')
            { checkS1=1; break; }
        }
        
        for (int i=0; i<s2.length(); i++)
        {
            char c2=s2.charAt(i);
            if (c2=='*' || c2=='/' || c2=='.' || c2==',' || c2==';' || c2=='?' || c2=='!'
                    || c2=='&' || c2=='$' || c2=='#')
            { checkS2=1; break; }
        }
        
        for (int i=0; i<s3.length(); i++)
        {
            char c3=s3.charAt(i);
            if (c3=='*' || c3=='/' || c3=='.' || c3==',' || c3==';' || c3=='?' || c3=='!'
                    || c3=='&' || c3=='$' || c3=='#')
            { checkS3=1; break; }
        }
        
              
        int a=0;
    for (int i=0; i<arr.size(); i++)
    {
        if ((jTextField2.getText()).equals(arr.get(i).passenger.passportNum))
        {
            a=1;
            break;
        }
    }
        
        
    if (b==true)
    {
         jButton1.setVisible(true);
         jButton1.setText("ERROR! FILL ALL DETAILS");
    }
    
    else if (checkS1!=0 || checkS2!=0 || checkS3!=0)
    {
        jButton1.setVisible(true);
         jButton1.setText("ERROR! NO SPECIAL CHARACTERS!");
    }
    
    else if ((jComboBox1.getSelectedItem()).equals(jComboBox2.getSelectedItem()))
    {
        jButton1.setVisible(true);
         jButton1.setText("ERROR! PICK A DIFFERENT DESTINATION");
    }
    
    else if (a==1)
    {
        jButton1.setVisible(true);
        jButton1.setText("ERROR! THIS PERSON ALREADY HAS BOOKED A TICKET");
    }
    
    else 
    {
        jButton1.setVisible(false);
        String org=(String)(jComboBox2.getSelectedItem());
        String des=(String)(jComboBox1.getSelectedItem());
        String date=jTextField3.getText();
        String name=jTextField1.getText();
        String pNum=jTextField2.getText();
        int lug=jSlider1.getValue();
        boolean isRoundTrip=true;
        double fare1=0.0;
        
        if ((jComboBox4.getSelectedItem()).equals("ONE-WAY"))
        { isRoundTrip=false; }
        else { isRoundTrip=true; }
        
        if ((jComboBox3.getSelectedItem()).equals("ECONOMY"))
        {
            Economy e=new Economy(org,des,date,name,pNum,isRoundTrip,lug);
            fare1=e.fare;
            arr.add(e);
        }
        
        else if((jComboBox3.getSelectedItem()).equals("BUSINESS"))
        {
            Business bs=new Business(org,des,date,name,pNum,isRoundTrip,lug);
            fare1=bs.fare;
            arr.add(bs);
        }
        
        else
        {
            First fs=new First(org,des,date,name,pNum,isRoundTrip,lug);
            fare1=fs.fare;
            arr.add(fs);
        }
        
        arr.get(0).saveArraylistToFile(arr);
        String f1=Double.toString(fare1);
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jLabel13.setText(f1);
    }
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
