/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;
import java.util.ArrayList;
import java.io.File;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Ibrahim
 */
public class Form3 extends javax.swing.JFrame {
    
    ArrayList<Ticket> arr;
    static String pN="";

    /**
     * Creates new form Form3
     */
    public Form3() {
        initComponents();
        jPanel1.setVisible(false); 
        jLabel23.setVisible(false); 
    }
    
    public Form3(ArrayList<Ticket> arr) {
        initComponents();
        jPanel1.setVisible(false);
        jLabel23.setVisible(false);
        this.arr=arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 730));
        setMinimumSize(new java.awt.Dimension(750, 730));
        setPreferredSize(new java.awt.Dimension(750, 730));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(90, 227, 200));
        jLabel1.setText("VIEW TICKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 200, 58));

        jButton1.setBackground(new java.awt.Color(2, 145, 116));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< MAIN MENU");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 40));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSPORT NUMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, 36));

        jTextField1.setBackground(new java.awt.Color(5, 17, 21));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 190, 40));

        jButton2.setBackground(new java.awt.Color(2, 145, 116));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 160, 40));

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 27)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("SORRY. NO TICKET HAS BEEN BOOKED USING THIS PASSPORT");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 750, 170));

        jPanel1.setBackground(new java.awt.Color(17, 40, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FIRST");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 220, 40));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FL-123");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 190, 40));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("DURATION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 20));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("TO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 20));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 80, 20));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("FROM");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 20));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("BOARDING GATE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, 20));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("SEAT NUMBER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 160, 20));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 145, 116));
        jLabel13.setText("F-77");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 150, 20));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 145, 116));
        jLabel14.setText("NEW YORK (JFK)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, 20));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 145, 116));
        jLabel15.setText("ZURICH (ZRH)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, 20));

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 145, 116));
        jLabel16.setText("5");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 50, 20));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 145, 116));
        jLabel17.setText("G5");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 120, 20));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 145, 116));
        jLabel18.setText("IBRAHIM");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 230, 20));

        jButton3.setBackground(new java.awt.Color(2, 145, 116));
        jButton3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 320, -1));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("DATE");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, 20));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 145, 116));
        jLabel20.setText("01-JAN");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 20));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("LUGGAGE (KG)");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 20));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(2, 145, 116));
        jLabel22.setText("ONE-WAY");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 130, 20));

        jLabel4.setBackground(new java.awt.Color(17, 40, 46));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 690, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 700, 510));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Package1/back3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Form1 f1=new Form1(arr);
        f1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int check=0,index=0;

for (int i=0; i<arr.size(); i++)
{
 if((arr.get(i).passenger.passportNum).equals(jTextField1.getText()))
 {
     check=1;
     index=i;
     pN=jTextField1.getText();
     break;
 }
}
      if(check==1) 
      { 
          jPanel1.setVisible(true); 
          jLabel23.setVisible(false);
          (arr.get(index)).viewTicket(this);
      }
      
      else if (check==0 && (jTextField1.getText()).equals(""))
      {
          jPanel1.setVisible(false); 
          jLabel23.setVisible(true);
          jLabel23.setText("PLEASE ENTER A PASSPORT NUMBER");
      }
      else if (check==0 && !(jTextField1.getText()).equals(""))
      {
          jPanel1.setVisible(false); 
          jLabel23.setVisible(true);
          jLabel23.setText("SORRY. NO TICKET HAS BEEN BOOKED USING THIS PASSPORT");
      }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        for (int i=0; i<arr.size(); i++)
        {
            if ((arr.get(i).passenger.passportNum).equals(pN))
            {
                (arr.get(i)).printTicket();
                break;
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }
    
    public javax.swing.JLabel getLabel13() { return jLabel13; }
    public javax.swing.JLabel getLabel14() { return jLabel14; }
    public javax.swing.JLabel getLabel15() { return jLabel15; }
    public javax.swing.JLabel getLabel16() { return jLabel16; }
    public javax.swing.JLabel getLabel17() { return jLabel17; }
    public javax.swing.JLabel getLabel18() { return jLabel18; }
    public javax.swing.JLabel getLabel20() { return jLabel20; }
    public javax.swing.JLabel getLabel22() { return jLabel22; }
    public javax.swing.JLabel getLabel5() { return jLabel5; }
    public javax.swing.JLabel getLabel6() { return jLabel6; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
